on:
  webhook:  
    method: post
jobs:
    - name: create-json
      id: create-json
      uses: jsdaniell/create-json@1.1.2
      with:
        name: "new-json-file.json"
        json: '{"name":"jsdaniell", "password":"mypass"}'
