on:
  webhook:  
    method: post
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: create-json
        id: create-json
        uses: DamianReeves/write-file-action
        with:
          path: ${{ env.home}}/driver.json
          contents: |
            echo "Hello World!"
          write-mode: append
